apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftpgo-vol02
  namespace: sftpgo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-cephfs-sc
  volumeMode: Filesystem
