apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftpgo-users-home
  namespace: sftpgo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-cephfs-sc
  volumeMode: Filesystem
