- name: create ansible group
  ansible.builtin.group:
    name: ansible
    gid: 2000

- name: create ansible user
  ansible.builtin.user:
    name: ansible
    comment: "Ansible configuration user"
    group: ansible
    uid: 2000

- name: create sudoers entry
  community.general.sudoers:
    name: ansible-become
    state: present
    user: ansible
    runas: root
    commands: ALL

- name: change ansible-admin password
  ansible.builtin.user:
    name: ansible-admin
    password: "{{ vault.init_admin_password | password_hash('sha512') }}"

- name: create ssh directory
  file:
    path: /home/ansible/.ssh
    state: directory
    owner: ansible
    group: ansible

- name: mutate hostname
  set_fact:
    m_host: "{{ ansible_host | replace('-','_') }}"

- name: copy ssh public key to user dir
  copy:
    content: "{{ vault.ssh_keys_public[m_host] | b64decode }}"
    dest: /home/ansible/.ssh/authorized_keys
    mode: '0600'
    owner: ansible
    group: ansible

- name: write ssh config file
  template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: '0644'
    owner: root
  notify: "h-sshd-restart"
