- name: stop & disable WIFI
  service:
    name: wpa_supplicant
    state: stopped
    enabled: false

- name: stop & disable Bluetooth
  service:
    name: bluetooth
    state: stopped
    enabled: false

- name: stop & disable Bluetooth dev
  ignore_errors: true
  service:
    name: hciuart
    state: stopped
    enabled: false

- name: stop & disable modem (e.g. 4G)
  service:
    name: ModemManager
    state: stopped
    enabled: false

- name: stop & disable hotkey function
  ignore_errors: true
  service:
    name: triggerhappy
    state: stopped
    enabled: false

- name: mask APT daily
  shell: systemctl mask apt-daily
  args:
    executable: /bin/bash

- name: mask APT daily-upgrade
  shell: systemctl mask apt-daily-upgrade
  args:
    executable: /bin/bash

- name: stop & disable APT daily timer
  service:
    name: apt-daily.timer
    state: stopped
    enabled: false

- name: stop & disable APT daily upgrade timer
  service:
    name: apt-daily-upgrade.timer
    state: stopped
    enabled: false

- name: remove man-db updates
  file:
    path: /var/lib/man-db/auto-update
    state: absent

- name: disable swap
  shell: swapoff -a
  args:
    executable: /bin/bash

- name: mask swap service
  shell: systemctl mask swap.target
  args:
    executable: /bin/bash

- name: stop & disable swap service
  service:
    name: swap.target
    state: stopped
    enabled: false
