- hosts: hl_master, hl_worker, hl_lb, hl_ceph
  become: yes
  become_method: sudo
  remote_user: ansible-admin
  vars:
    ansible_ssh_private_key_file: /datadisk/05_credentials/ssh-keys/admin.private
  roles:
    - admin_get_temperature
