- hosts: hl-lb-01
  become: yes
  become_method: sudo
  remote_user: ansible-admin
  vars:
    ansible_ssh_private_key_file: /datadisk/05_credentials/ssh-keys/admin.private
  vars_files:
    - "vault/av_homelab"
  roles:
    - admin_distribute_sshkeys
  handlers:
  - name: h-sshd-restart
    systemd_service:
      name: sshd
      state: restarted
      daemon_reload: true
