- hosts: hl-lb-01
  gather_facts: False
  become: True
  become_method: sudo
  remote_user: ansible
  vars_files:
    - "vault/av_homelab"
  roles:
    - expose_ssh_keys
    - setup_haproxy
    - setup_wireguard
  handlers:
  - name: h-clean-exposed-keys
    delegate_to: localhost
    file:
      name: /tmp/ansible_exposed_keys
      state: absent
  - name: "h-restart-haproxy"
    service:
      name: haproxy
      state: restarted
  - name: "h-restart-keepalived"
    service:
      name: keepalived
      state: restarted
