- hosts: hl-lb-01
  become: yes
  become_method: sudo
  remote_user: ansible
  vars_files:
    - "vault/av_homelab"
  roles:
    - expose_ssh_keys
    - setup_haproxy
    - setup_wireguard
  handlers:
  - name: h-clean-exposed-keys
    delegate_to: localhost
    file:
      name: /tmp/ansible_exposed_keys
      state: absent
