- name: write ssh config file
  template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: '0644'
    owner: root
  changed_when: True
  notify: "h-sshd-restart"
  when: op_mode == "install"

- name: get ceph private ssh key to directory
  copy:
    content: "{{ vault.ceph.ssh_key_private | b64decode }}"
    dest: /root/.ssh/id_ed25519
    mode: '0600'
    owner: root
    group: root
  when: op_mode == "install"

- name: write ceph public key to authorized keys and overwrite all old entries
  copy:
    content: "{{  vault.ceph.ssh_key_public | b64decode }}"
    dest: /root/.ssh/authorized_keys
    mode: '0600'
    owner: root
    group: root
  when: op_mode == "install"
