- name: install haproxy package
  package:
    name: haproxy
    state: present
  when: op_mode == "install"

- name: get config template to directory
  template:
    src: "templates/haproxy.cfg.j2"
    dest: /etc/haproxy/haproxy.cfg
  when: op_mode == "install"

- name: deinstall haproxy package
  package:
    name: haproxy
    state: absent
  when: op_mode == "uninstall"

- name: remove config directory
  file:
    path: /etc/haproxy
    state: absent
  when: op_mode == "uninstall"
