[hl_k3s]
hl-k3s-01
hl-k3s-02
hl-k3s-03

[hl_lb]
hl-lb-01
hl-lb-02

[hl_k8s]
hl-k8s-01
hl-k8s-02
hl-k8s-03
hl-k8s-04
hl-k8s-05
hl-k8s-06
hl-k8s-07
hl-k8s-08
hl-k8s-09
hl-k8s-10

[hl_ceph]
hl-ceph-01
hl-ceph-02
hl-ceph-03
hl-ceph-04
hl-ceph-05
