- name: install keepalived package
  package:
    name: keepalived
    state: present
  when: op_mode == "install"

- name: get config template to directory
  template:
    src: "templates/keepalived.conf.j2"
    dest: /etc/keepalived/keepalived.conf
  changed_when: True
  notify: "h-restart-keepalived"
  when: op_mode == "install" or op_mode == "config-update"

- name: deinstall keepalived package
  package:
    name: keepalived
    state: absent
  when: op_mode == "uninstall"

- name: remove config directory
  file:
    path: /etc/keepalived
    state: absent
  when: op_mode == "uninstall"